// Données de démonstration — identiques au classeur Excel V3.1 (avril-juin 2026)
export const DEMO_ACTES = [
  {
    "numero_minute": "2026/0201",
    "numero_dossier": "D-2026-055",
    "date_ouverture": "2026-04-02",
    "date_echeance": "2026-04-22",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "COCODY",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 35000000,
    "honoraires_totaux": 2290000,
    "montant_regle": 2290000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": "Signé le 24/04",
    "parties": [
      "M. Kouadio A.",
      "Mme Brou S."
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 1832000,
    "droits_etat": 343500,
    "debours": 114500,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0202",
    "numero_dossier": "D-2026-056",
    "date_ouverture": "2026-04-06",
    "date_echeance": "2026-10-03",
    "nature_acte": "Succession",
    "complexite": "Complexe",
    "responsable": "Le Notaire",
    "conservation_fonciere": "BOUAKE",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 80000000,
    "honoraires_totaux": 1940000,
    "montant_regle": 1940000,
    "statut_paiement": "Réglé",
    "difficultes": "Recherche d'un héritier à l'étranger",
    "observations": "Clôturé le 12/06",
    "parties": [
      "Héritiers Konan Y."
    ],
    "piece": null,
    "saisi": "Clerc 1",
    "emoluments": 1552000,
    "droits_etat": 291000,
    "debours": 97000,
    "depenses_formalites": 120000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0203",
    "numero_dossier": "D-2026-057",
    "date_ouverture": "2026-04-09",
    "date_echeance": "2026-04-29",
    "nature_acte": "Bail",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "PLATEAU",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 12000000,
    "honoraires_totaux": 264000,
    "montant_regle": 264000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "SCI Palmier",
      "SARL Cacao Plus"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 211200,
    "droits_etat": 39600,
    "debours": 13200,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0204",
    "numero_dossier": "D-2026-058",
    "date_ouverture": "2026-04-13",
    "date_echeance": "2026-05-03",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "SONGON",
    "progression": "Réception de l'état foncier",
    "fini": false,
    "valeur_acte": 18000000,
    "honoraires_totaux": 1636000,
    "montant_regle": 0,
    "statut_paiement": "Non réglé",
    "difficultes": "Litige de bornage avec le voisin",
    "observations": "Dossier sensible — suivre de près",
    "parties": [
      "M. Traoré I.",
      "M. Bamba L."
    ],
    "piece": "Plan de bornage",
    "saisi": "Clerc 1",
    "emoluments": 1308800,
    "droits_etat": 245400,
    "debours": 81800,
    "depenses_formalites": 85000,
    "statut_formalites": "Débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0205",
    "numero_dossier": "D-2026-059",
    "date_ouverture": "2026-04-16",
    "date_echeance": "2026-05-06",
    "nature_acte": "Donation",
    "complexite": "Simple",
    "responsable": "Clerc 3",
    "conservation_fonciere": "BINGERVILLE",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 25000000,
    "honoraires_totaux": 1625000,
    "montant_regle": 1625000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "M. Assi P. → ses enfants"
    ],
    "piece": null,
    "saisi": "Accueil",
    "emoluments": 1300000,
    "droits_etat": 243750,
    "debours": 81250,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0206",
    "numero_dossier": "D-2026-060",
    "date_ouverture": "2026-04-20",
    "date_echeance": "2026-05-10",
    "nature_acte": "Société",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "TREICHVILLE",
    "progression": "Annulé",
    "fini": true,
    "valeur_acte": 0,
    "honoraires_totaux": 250000,
    "montant_regle": 250000,
    "statut_paiement": "Réglé",
    "difficultes": "Associés en désaccord",
    "observations": "Annulé à la demande des parties le 15/05",
    "parties": [
      "SARL Ivoire Négoce"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 0,
    "droits_etat": 0,
    "debours": 250000,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0207",
    "numero_dossier": "D-2026-061",
    "date_ouverture": "2026-04-22",
    "date_echeance": "2026-05-12",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "MARCORY",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 42000000,
    "honoraires_totaux": 2604000,
    "montant_regle": 2604000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Mme Ouattara F.",
      "M. Koné D."
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 2083200,
    "droits_etat": 390600,
    "debours": 130200,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0208",
    "numero_dossier": "D-2026-062",
    "date_ouverture": "2026-04-24",
    "date_echeance": "2026-05-24",
    "nature_acte": "Ouverture de Crédit",
    "complexite": "Complexe",
    "responsable": "Le Notaire",
    "conservation_fonciere": "RIVIERA",
    "progression": "Dépôt des formalités",
    "fini": false,
    "valeur_acte": 55000000,
    "honoraires_totaux": 1610000,
    "montant_regle": 0,
    "statut_paiement": "Non réglé",
    "difficultes": "Attente mainlevée de la banque",
    "observations": "Relancer la banque chaque semaine",
    "parties": [
      "Banque Atlantique",
      "M. Gnamba T."
    ],
    "piece": "Quitus fiscal",
    "saisi": "Clerc 2",
    "emoluments": 1288000,
    "droits_etat": 241500,
    "debours": 80500,
    "depenses_formalites": 50000,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0209",
    "numero_dossier": "D-2026-063",
    "date_ouverture": "2026-04-27",
    "date_echeance": "2026-10-24",
    "nature_acte": "Succession",
    "complexite": "Simple",
    "responsable": "Clerc 3",
    "conservation_fonciere": "ABOBO",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 15000000,
    "honoraires_totaux": 330000,
    "montant_regle": 330000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Héritiers Mme Adjoua B."
    ],
    "piece": null,
    "saisi": "Accueil",
    "emoluments": 264000,
    "droits_etat": 49500,
    "debours": 16500,
    "depenses_formalites": 85000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0210",
    "numero_dossier": "D-2026-064",
    "date_ouverture": "2026-04-29",
    "date_echeance": "2026-05-19",
    "nature_acte": "Autres",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "YOPOUGON 1",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 0,
    "honoraires_totaux": 300000,
    "montant_regle": 300000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Famille Ekra"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 240000,
    "droits_etat": 45000,
    "debours": 15000,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0211",
    "numero_dossier": "D-2026-065",
    "date_ouverture": "2026-05-04",
    "date_echeance": "2026-06-03",
    "nature_acte": "Vente",
    "complexite": "Complexe",
    "responsable": "Le Notaire",
    "conservation_fonciere": "COCODY",
    "progression": "Signature",
    "fini": false,
    "valeur_acte": 95000000,
    "honoraires_totaux": 6410000,
    "montant_regle": 0,
    "statut_paiement": "Non réglé",
    "difficultes": "Acheteur en France — procuration en cours",
    "observations": "Signature prévue mi-juillet",
    "parties": [
      "SCI Horizon",
      "M. Diabaté M."
    ],
    "piece": "Procuration",
    "saisi": "Clerc 1",
    "emoluments": 5128000,
    "droits_etat": 961500,
    "debours": 320500,
    "depenses_formalites": 85000,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0212",
    "numero_dossier": "D-2026-066",
    "date_ouverture": "2026-05-07",
    "date_echeance": "2026-11-03",
    "nature_acte": "Succession",
    "complexite": "Complexe",
    "responsable": "Clerc 1",
    "conservation_fonciere": "YAMOUSSOUKRO",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 60000000,
    "honoraires_totaux": 1670000,
    "montant_regle": 1670000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": "Clôturé le 30/06",
    "parties": [
      "Héritiers N'Dri K."
    ],
    "piece": null,
    "saisi": "Clerc 1",
    "emoluments": 1336000,
    "droits_etat": 250500,
    "debours": 83500,
    "depenses_formalites": 120000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0213",
    "numero_dossier": "D-2026-067",
    "date_ouverture": "2026-05-11",
    "date_echeance": "2026-05-31",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "DABOU",
    "progression": "Réception de l'état foncier",
    "fini": false,
    "valeur_acte": 9000000,
    "honoraires_totaux": 808000,
    "montant_regle": 626655,
    "statut_paiement": "Partiel",
    "difficultes": "Attestation villageoise difficile à obtenir",
    "observations": null,
    "parties": [
      "M. Séka J.",
      "Mme Amon C."
    ],
    "piece": "Attestation villageoise",
    "saisi": "Secrétariat",
    "emoluments": 646400,
    "droits_etat": 121200,
    "debours": 40400,
    "depenses_formalites": 0,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0214",
    "numero_dossier": "D-2026-068",
    "date_ouverture": "2026-05-13",
    "date_echeance": "2026-06-02",
    "nature_acte": "Bail",
    "complexite": "Simple",
    "responsable": "Clerc 3",
    "conservation_fonciere": "ADZOPE",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 8000000,
    "honoraires_totaux": 226000,
    "montant_regle": 226000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "M. Fofana S.",
      "Pharmacie du Marché"
    ],
    "piece": null,
    "saisi": "Accueil",
    "emoluments": 180800,
    "droits_etat": 33900,
    "debours": 11300,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0215",
    "numero_dossier": "D-2026-069",
    "date_ouverture": "2026-05-15",
    "date_echeance": "2026-06-04",
    "nature_acte": "Donation",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "GRAND-BASSAM",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 20000000,
    "honoraires_totaux": 1350000,
    "montant_regle": 1350000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Mme Tanoh E. → sa fille"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 1080000,
    "droits_etat": 202500,
    "debours": 67500,
    "depenses_formalites": 0,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0216",
    "numero_dossier": "D-2026-070",
    "date_ouverture": "2026-05-18",
    "date_echeance": "2026-06-07",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "PLATEAU",
    "progression": "Rédaction",
    "fini": false,
    "valeur_acte": 30000000,
    "honoraires_totaux": 1980000,
    "montant_regle": 636540,
    "statut_paiement": "Partiel",
    "difficultes": "Titre foncier introuvable côté vendeur",
    "observations": "⚠ Dossier bloqué — voir le Notaire",
    "parties": [
      "M. Koffi R.",
      "M. Zadi B."
    ],
    "piece": "Titre foncier",
    "saisi": "Clerc 2",
    "emoluments": 1584000,
    "droits_etat": 297000,
    "debours": 99000,
    "depenses_formalites": 50000,
    "statut_formalites": "En cours",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0217",
    "numero_dossier": "D-2026-071",
    "date_ouverture": "2026-05-20",
    "date_echeance": "2026-06-09",
    "nature_acte": "Société",
    "complexite": "Simple",
    "responsable": "Le Notaire",
    "conservation_fonciere": "TREICHVILLE",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 5000000,
    "honoraires_totaux": 175000,
    "montant_regle": 175000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "SAS Karité d'Or"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 140000,
    "droits_etat": 26250,
    "debours": 8750,
    "depenses_formalites": 85000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0218",
    "numero_dossier": "D-2026-072",
    "date_ouverture": "2026-05-22",
    "date_echeance": "2026-11-18",
    "nature_acte": "Succession",
    "complexite": "Complexe",
    "responsable": "Clerc 3",
    "conservation_fonciere": "DIVO",
    "progression": "Annulé",
    "fini": true,
    "valeur_acte": 0,
    "honoraires_totaux": 120000,
    "montant_regle": 120000,
    "statut_paiement": "Réglé",
    "difficultes": "Famille retirée du dossier",
    "observations": "Annulé le 20/06",
    "parties": [
      "Héritiers Aka P."
    ],
    "piece": "Acte de naissance",
    "saisi": "Clerc 3",
    "emoluments": 0,
    "droits_etat": 0,
    "debours": 120000,
    "depenses_formalites": 85000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0219",
    "numero_dossier": "D-2026-073",
    "date_ouverture": "2026-05-26",
    "date_echeance": "2026-06-15",
    "nature_acte": "Ouverture de Crédit",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "MARCORY",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 28000000,
    "honoraires_totaux": 1248000,
    "montant_regle": 1248000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "SGBCI",
      "Mme Yao A."
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 998400,
    "droits_etat": 187200,
    "debours": 62400,
    "depenses_formalites": 120000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0220",
    "numero_dossier": "D-2026-074",
    "date_ouverture": "2026-05-28",
    "date_echeance": "2026-06-27",
    "nature_acte": "Vente",
    "complexite": "Complexe",
    "responsable": "Le Notaire",
    "conservation_fonciere": "RIVIERA",
    "progression": "Préparation des formalités",
    "fini": false,
    "valeur_acte": 70000000,
    "honoraires_totaux": 4390000,
    "montant_regle": 1381260,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "M. Coulibaly Z.",
      "SCI Baobab"
    ],
    "piece": "CNI / Pièce d'identité",
    "saisi": "Clerc 2",
    "emoluments": 3512000,
    "droits_etat": 658500,
    "debours": 219500,
    "depenses_formalites": 0,
    "statut_formalites": "Débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0221",
    "numero_dossier": "D-2026-075",
    "date_ouverture": "2026-06-05",
    "date_echeance": "2026-06-25",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "SONGON",
    "progression": "Dépôt des formalités",
    "fini": false,
    "valeur_acte": 11000000,
    "honoraires_totaux": 682000,
    "montant_regle": 0,
    "statut_paiement": "Non réglé",
    "difficultes": null,
    "observations": null,
    "parties": [
      "M. Guei F.",
      "M. Ballo O."
    ],
    "piece": "Plan de bornage",
    "saisi": "Secrétariat",
    "emoluments": 545600,
    "droits_etat": 102300,
    "debours": 34100,
    "depenses_formalites": 85000,
    "statut_formalites": "En cours",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0222",
    "numero_dossier": "D-2026-076",
    "date_ouverture": "2026-06-09",
    "date_echeance": "2026-12-06",
    "nature_acte": "Succession",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "ABENGOUROU",
    "progression": "Rédaction",
    "fini": false,
    "valeur_acte": 22000000,
    "honoraires_totaux": 484000,
    "montant_regle": 196836,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Héritiers Kacou L."
    ],
    "piece": "Certificat de mariage",
    "saisi": "Accueil",
    "emoluments": 387200,
    "droits_etat": 72600,
    "debours": 24200,
    "depenses_formalites": 85000,
    "statut_formalites": "Débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0223",
    "numero_dossier": "D-2026-077",
    "date_ouverture": "2026-06-12",
    "date_echeance": "2026-07-02",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 3",
    "conservation_fonciere": "KORHOGO",
    "progression": "Terminé",
    "fini": true,
    "valeur_acte": 16000000,
    "honoraires_totaux": 1342000,
    "montant_regle": 1342000,
    "statut_paiement": "Réglé",
    "difficultes": null,
    "observations": "Dossier éclair — 10 jours",
    "parties": [
      "Mme Ahoua V.",
      "M. Djè K."
    ],
    "piece": null,
    "saisi": "Clerc 3",
    "emoluments": 1073600,
    "droits_etat": 201300,
    "debours": 67100,
    "depenses_formalites": 85000,
    "statut_formalites": "Terminé",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0224",
    "numero_dossier": "D-2026-078",
    "date_ouverture": "2026-06-15",
    "date_echeance": "2026-07-05",
    "nature_acte": "Bail",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "COCODY",
    "progression": "Rédaction",
    "fini": false,
    "valeur_acte": 10000000,
    "honoraires_totaux": 400000,
    "montant_regle": 334950,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "SCI Lagune",
      "Restaurant Chez Tantie"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 320000,
    "droits_etat": 60000,
    "debours": 20000,
    "depenses_formalites": 25000,
    "statut_formalites": "En cours",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0225",
    "numero_dossier": "D-2026-079",
    "date_ouverture": "2026-06-18",
    "date_echeance": "2026-07-18",
    "nature_acte": "Vente",
    "complexite": "Complexe",
    "responsable": "Le Notaire",
    "conservation_fonciere": "BOUAKE",
    "progression": "Paiement",
    "fini": false,
    "valeur_acte": 48000000,
    "honoraires_totaux": 3156000,
    "montant_regle": 1663940,
    "statut_paiement": "Partiel",
    "difficultes": "Frais d'enregistrement en attente",
    "observations": "Relancer l'acheteur",
    "parties": [
      "M. Ipou G.",
      "Mme Sanogo W."
    ],
    "piece": "Quitus fiscal",
    "saisi": "Clerc 1",
    "emoluments": 2524800,
    "droits_etat": 473400,
    "debours": 157800,
    "depenses_formalites": 25000,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0226",
    "numero_dossier": "D-2026-080",
    "date_ouverture": "2026-06-22",
    "date_echeance": "2026-07-12",
    "nature_acte": "Donation",
    "complexite": "Simple",
    "responsable": "Clerc 1",
    "conservation_fonciere": "AGBOVILLE",
    "progression": "Rédaction",
    "fini": false,
    "valeur_acte": 18000000,
    "honoraires_totaux": 1510000,
    "montant_regle": 472440,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "M. Bictogo H. → son neveu"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 1208000,
    "droits_etat": 226500,
    "debours": 75500,
    "depenses_formalites": 0,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0227",
    "numero_dossier": "D-2026-081",
    "date_ouverture": "2026-06-24",
    "date_echeance": "2026-07-14",
    "nature_acte": "Autres",
    "complexite": "Simple",
    "responsable": "Clerc 3",
    "conservation_fonciere": "GAGNOA",
    "progression": "Recensement des informations",
    "fini": false,
    "valeur_acte": 0,
    "honoraires_totaux": 370000,
    "montant_regle": 312450,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Famille Gbagbo N."
    ],
    "piece": "Acte de naissance",
    "saisi": "Accueil",
    "emoluments": 296000,
    "droits_etat": 55500,
    "debours": 18500,
    "depenses_formalites": 25000,
    "statut_formalites": "Débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0228",
    "numero_dossier": "D-2026-082",
    "date_ouverture": "2026-06-27",
    "date_echeance": "2026-07-17",
    "nature_acte": "Vente",
    "complexite": "Simple",
    "responsable": "Clerc 2",
    "conservation_fonciere": "BINGERVILLE",
    "progression": "Rédaction",
    "fini": false,
    "valeur_acte": 26000000,
    "honoraires_totaux": 1962000,
    "montant_regle": 1045780,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "Mme Kramo J.",
      "M. Ano B."
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 1569600,
    "droits_etat": 294300,
    "debours": 98100,
    "depenses_formalites": 50000,
    "statut_formalites": "En cours",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0229",
    "numero_dossier": "D-2026-083",
    "date_ouverture": "2026-06-30",
    "date_echeance": "2026-07-20",
    "nature_acte": "Société",
    "complexite": "Simple",
    "responsable": "Le Notaire",
    "conservation_fonciere": "YOPOUGON 2",
    "progression": "Recensement des informations",
    "fini": false,
    "valeur_acte": 4000000,
    "honoraires_totaux": 140000,
    "montant_regle": 113100,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": null,
    "parties": [
      "SARL Attiéké Premium"
    ],
    "piece": null,
    "saisi": "Secrétariat",
    "emoluments": 112000,
    "droits_etat": 21000,
    "debours": 7000,
    "depenses_formalites": 0,
    "statut_formalites": "Pas encore débuté",
    "autres_depenses": 0
  },
  {
    "numero_minute": "2026/0230",
    "numero_dossier": "D-2026-084",
    "date_ouverture": "2026-07-02",
    "date_echeance": "2026-12-29",
    "nature_acte": "Succession",
    "complexite": "Complexe",
    "responsable": "Clerc 1",
    "conservation_fonciere": "MAN",
    "progression": "Recensement des informations",
    "fini": false,
    "valeur_acte": 45000000,
    "honoraires_totaux": 1510000,
    "montant_regle": 513960,
    "statut_paiement": "Partiel",
    "difficultes": null,
    "observations": "Nouveau dossier",
    "parties": [
      "Héritiers Mme Bohoussou D."
    ],
    "piece": "Titre foncier",
    "saisi": "Accueil",
    "emoluments": 1208000,
    "droits_etat": 226500,
    "debours": 75500,
    "depenses_formalites": 25000,
    "statut_formalites": "Débuté",
    "autres_depenses": 0
  }
];

export const DEMO_APPELS = [
 {
  "numero": 1,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-03",
  "heure": "08:20",
  "reference_dossier": "2026/0201",
  "client_nom": "M. Kouadio A.",
  "telephone": "07 08 12 34 56",
  "email": null,
  "destinataire": "Clerc 1",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Avancement de la vente Cocody",
  "saisi": "Accueil"
 },
 {
  "numero": 2,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-07",
  "heure": "09:45",
  "reference_dossier": "2026/0202",
  "client_nom": "Mme Konan G.",
  "telephone": "05 44 22 18 90",
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Nouvelle demande",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Ouverture succession de son père",
  "saisi": "Accueil"
 },
 {
  "numero": 3,
  "type_flux": "Courrier Physique",
  "date_entree": "2026-04-09",
  "heure": "11:00",
  "reference_dossier": null,
  "client_nom": "Mairie de Cocody",
  "telephone": null,
  "email": null,
  "destinataire": "Formaliste",
  "motif": "Renseignement général",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Demande d'attestation — Répondu par courrier du 15/04",
  "saisi": "Secrétariat"
 },
 {
  "numero": 4,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-14",
  "heure": "14:30",
  "reference_dossier": "2026/0204",
  "client_nom": "M. Traoré I.",
  "telephone": "01 02 55 66 77",
  "email": null,
  "destinataire": "Clerc 1",
  "motif": "Réclamation",
  "statut_traitement": "Résolu",
  "nb_tentatives": 2,
  "resolu": true,
  "observations": "Conteste le bornage du voisin — Rendez-vous fixé",
  "saisi": "Accueil"
 },
 {
  "numero": 5,
  "type_flux": "Courrier Électronique",
  "date_entree": "2026-04-16",
  "heure": "10:15",
  "reference_dossier": null,
  "client_nom": "Mme Assi C.",
  "telephone": null,
  "email": "c.assi@exemple.ci",
  "destinataire": "Clerc 3",
  "motif": "Demande de rendez-vous",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Projet de donation aux enfants",
  "saisi": "Secrétariat"
 },
 {
  "numero": 6,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-18",
  "heure": "16:05",
  "reference_dossier": "2026/0206",
  "client_nom": "M. Dosso B.",
  "telephone": "07 77 88 99 00",
  "email": null,
  "destinataire": "Clerc 2",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Statuts de la SARL",
  "saisi": "Accueil"
 },
 {
  "numero": 7,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-21",
  "heure": "08:50",
  "reference_dossier": null,
  "client_nom": "Mme Bakayoko S.",
  "telephone": "05 11 22 33 44",
  "email": null,
  "destinataire": "Comptabilité",
  "motif": "Relance paiement",
  "statut_traitement": "Résolu",
  "nb_tentatives": 3,
  "resolu": true,
  "observations": "Facture d'honoraires impayée — Payé le 30/04",
  "saisi": "Comptabilité"
 },
 {
  "numero": 8,
  "type_flux": "Courrier Physique",
  "date_entree": "2026-04-23",
  "heure": "09:30",
  "reference_dossier": "2026/0208",
  "client_nom": "Banque Atlantique",
  "telephone": null,
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Pièces du prêt hypothécaire",
  "saisi": "Secrétariat"
 },
 {
  "numero": 9,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-27",
  "heure": "15:40",
  "reference_dossier": null,
  "client_nom": "M. Yeboua T.",
  "telephone": "01 55 44 33 22",
  "email": null,
  "destinataire": "Accueil",
  "motif": "Géo-localisation",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Cherche l'adresse de l'étude",
  "saisi": "Accueil"
 },
 {
  "numero": 10,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-04-28",
  "heure": "11:20",
  "reference_dossier": "2026/0209",
  "client_nom": "Mme Adjoua-fille",
  "telephone": "07 99 00 11 22",
  "email": null,
  "destinataire": "Clerc 3",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "En attente du Clerc",
  "nb_tentatives": 4,
  "resolu": false,
  "observations": "Succession de sa mère — JAMAIS RAPPELÉE — ⚠ Dossier oublié — à traiter d'urgence",
  "saisi": "Accueil"
 },
 {
  "numero": 11,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-05",
  "heure": "09:10",
  "reference_dossier": "2026/0211",
  "client_nom": "M. Diabaté M.",
  "telephone": "+33 6 12 34 56 78",
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 2,
  "resolu": true,
  "observations": "Procuration depuis la France",
  "saisi": "Secrétariat"
 },
 {
  "numero": 12,
  "type_flux": "Courrier Électronique",
  "date_entree": "2026-05-08",
  "heure": "13:25",
  "reference_dossier": null,
  "client_nom": "SCI Horizon",
  "telephone": null,
  "email": "contact@sci-horizon.ci",
  "destinataire": "Clerc 1",
  "motif": "Nouvelle demande",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Achat immeuble Cocody",
  "saisi": "Secrétariat"
 },
 {
  "numero": 13,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-12",
  "heure": "10:00",
  "reference_dossier": "2026/0213",
  "client_nom": "M. Séka J.",
  "telephone": "05 66 77 88 99",
  "email": null,
  "destinataire": "Clerc 2",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 2,
  "resolu": true,
  "observations": "Attestation villageoise Dabou",
  "saisi": "Accueil"
 },
 {
  "numero": 14,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-14",
  "heure": "08:35",
  "reference_dossier": null,
  "client_nom": "Mme Gnaoré P.",
  "telephone": "07 12 21 12 21",
  "email": null,
  "destinataire": "Accueil",
  "motif": "Renseignement général",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Tarifs d'une vente de terrain",
  "saisi": "Accueil"
 },
 {
  "numero": 15,
  "type_flux": "Courrier Physique",
  "date_entree": "2026-05-18",
  "heure": "14:00",
  "reference_dossier": "2026/0216",
  "client_nom": "M. Koffi R.",
  "telephone": null,
  "email": null,
  "destinataire": "Clerc 2",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "En cours",
  "nb_tentatives": 2,
  "resolu": false,
  "observations": "Recherche du titre foncier — Titre toujours introuvable",
  "saisi": "Secrétariat"
 },
 {
  "numero": 16,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-20",
  "heure": "16:30",
  "reference_dossier": null,
  "client_nom": "M. Silué D.",
  "telephone": "01 34 43 34 43",
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Demande de rendez-vous",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Création SAS Karité d'Or",
  "saisi": "Accueil"
 },
 {
  "numero": 17,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-22",
  "heure": "09:55",
  "reference_dossier": "2026/0218",
  "client_nom": "M. Aka junior",
  "telephone": "05 87 78 87 78",
  "email": null,
  "destinataire": "Clerc 3",
  "motif": "Réclamation",
  "statut_traitement": "Résolu",
  "nb_tentatives": 2,
  "resolu": true,
  "observations": "Mécontent des délais succession — Famille finalement retirée",
  "saisi": "Accueil"
 },
 {
  "numero": 18,
  "type_flux": "Courrier Électronique",
  "date_entree": "2026-05-25",
  "heure": "11:45",
  "reference_dossier": null,
  "client_nom": "Notaire confrère Bouaké",
  "telephone": null,
  "email": "etude.bouake@exemple.ci",
  "destinataire": "Le Notaire",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Demande de copie d'acte",
  "saisi": "Secrétariat"
 },
 {
  "numero": 19,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-05-27",
  "heure": "15:15",
  "reference_dossier": "2026/0219",
  "client_nom": "Mme Yao A.",
  "telephone": "07 45 54 45 54",
  "email": null,
  "destinataire": "Clerc 1",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Prêt SGBCI — date de signature",
  "saisi": "Accueil"
 },
 {
  "numero": 20,
  "type_flux": "Courrier Physique",
  "date_entree": "2026-05-29",
  "heure": "10:30",
  "reference_dossier": null,
  "client_nom": "Direction des Impôts",
  "telephone": null,
  "email": null,
  "destinataire": "Comptabilité",
  "motif": "Renseignement général",
  "statut_traitement": "En cours",
  "nb_tentatives": 1,
  "resolu": false,
  "observations": "Demande d'état des enregistrements — ⚠ Réponse à préparer",
  "saisi": "Secrétariat"
 },
 {
  "numero": 21,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-06-10",
  "heure": "08:40",
  "reference_dossier": "2026/0222",
  "client_nom": "M. Kacou fils",
  "telephone": "05 23 32 23 32",
  "email": null,
  "destinataire": "Clerc 1",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Succession — certificat de mariage",
  "saisi": "Accueil"
 },
 {
  "numero": 22,
  "type_flux": "Courrier Électronique",
  "date_entree": "2026-06-15",
  "heure": "09:20",
  "reference_dossier": "2026/0224",
  "client_nom": "Restaurant Chez Tantie",
  "telephone": null,
  "email": "cheztantie@exemple.ci",
  "destinataire": "Clerc 2",
  "motif": "Nouvelle demande",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Bail du local Cocody",
  "saisi": "Secrétariat"
 },
 {
  "numero": 23,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-06-19",
  "heure": "14:50",
  "reference_dossier": "2026/0225",
  "client_nom": "M. Ipou G.",
  "telephone": "07 65 56 65 56",
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Relance paiement",
  "statut_traitement": "En attente du Clerc",
  "nb_tentatives": 3,
  "resolu": false,
  "observations": "Frais d'enregistrement impayés — 3e relance sans succès",
  "saisi": "Comptabilité"
 },
 {
  "numero": 24,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-06-25",
  "heure": "10:05",
  "reference_dossier": null,
  "client_nom": "Mme Touré K.",
  "telephone": "01 98 89 98 89",
  "email": null,
  "destinataire": "Accueil",
  "motif": "Renseignement général",
  "statut_traitement": "Résolu",
  "nb_tentatives": 1,
  "resolu": true,
  "observations": "Documents pour une donation",
  "saisi": "Accueil"
 },
 {
  "numero": 25,
  "type_flux": "Courrier Physique",
  "date_entree": "2026-06-26",
  "heure": "11:30",
  "reference_dossier": "2026/0227",
  "client_nom": "Sous-préfecture Gagnoa",
  "telephone": null,
  "email": null,
  "destinataire": "Clerc 3",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "En cours",
  "nb_tentatives": 1,
  "resolu": false,
  "observations": "Acte de naissance famille Gbagbo",
  "saisi": "Secrétariat"
 },
 {
  "numero": 26,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-06-29",
  "heure": "09:00",
  "reference_dossier": "2026/0228",
  "client_nom": "Mme Kramo J.",
  "telephone": "05 10 01 10 01",
  "email": null,
  "destinataire": "Clerc 2",
  "motif": "Suivi de dossier existant",
  "statut_traitement": "En attente du Clerc",
  "nb_tentatives": 2,
  "resolu": false,
  "observations": "Avancement vente Bingerville",
  "saisi": "Accueil"
 },
 {
  "numero": 27,
  "type_flux": "Courrier Électronique",
  "date_entree": "2026-06-30",
  "heure": "16:20",
  "reference_dossier": null,
  "client_nom": "M. Ouédraogo Z.",
  "telephone": null,
  "email": "z.ouedraogo@exemple.ci",
  "destinataire": "Le Notaire",
  "motif": "Nouvelle demande",
  "statut_traitement": "En cours",
  "nb_tentatives": 1,
  "resolu": false,
  "observations": "Achat terrain Yopougon — Devis à envoyer",
  "saisi": "Secrétariat"
 },
 {
  "numero": 28,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-07-01",
  "heure": "08:30",
  "reference_dossier": "2026/0230",
  "client_nom": "Héritier Bohoussou",
  "telephone": "07 31 13 31 13",
  "email": null,
  "destinataire": "Clerc 1",
  "motif": "Nouvelle demande",
  "statut_traitement": "En cours",
  "nb_tentatives": 1,
  "resolu": false,
  "observations": "Succession de sa mère — pièces à fournir — Liste des pièces envoyée",
  "saisi": "Accueil"
 },
 {
  "numero": 29,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-07-03",
  "heure": "10:45",
  "reference_dossier": null,
  "client_nom": "M. Amani F.",
  "telephone": "01 27 72 27 72",
  "email": null,
  "destinataire": "Accueil",
  "motif": "Demande de rendez-vous",
  "statut_traitement": "En attente du Clerc",
  "nb_tentatives": 1,
  "resolu": false,
  "observations": "Consultation création d'entreprise — RDV à caler cette semaine",
  "saisi": "Accueil"
 },
 {
  "numero": 30,
  "type_flux": "Appel Téléphonique",
  "date_entree": "2026-07-04",
  "heure": "08:15",
  "reference_dossier": null,
  "client_nom": "Mme Bléou M.",
  "telephone": "05 63 36 63 36",
  "email": null,
  "destinataire": "Le Notaire",
  "motif": "Nouvelle demande",
  "statut_traitement": "Non commencé",
  "nb_tentatives": 0,
  "resolu": false,
  "observations": "Vente d'une parcelle à Songon — Reçue ce matin",
  "saisi": "Accueil"
 }
];
