/** Référentiels par défaut appliqués à toute nouvelle étude provisionnée. */
export const REFERENTIELS_DEFAUT = [
  ["type_flux", "Appel Téléphonique"], ["type_flux", "Courrier Physique"], ["type_flux", "Courrier Électronique"],
  ["destinataire", "Le Notaire"], ["destinataire", "Clerc 1"], ["destinataire", "Clerc 2"],
  ["destinataire", "Clerc 3"], ["destinataire", "Comptabilité"], ["destinataire", "Formaliste"], ["destinataire", "Accueil"],
  ["motif", "Nouvelle demande"], ["motif", "Suivi dossier existant"], ["motif", "Réclamation"],
  ["motif", "RDV"], ["motif", "Renseignement général"], ["motif", "Relance paiement"], ["motif", "Géo-localisation"],
  ["statut_traitement", "Non commencé"], ["statut_traitement", "En cours"],
  ["statut_traitement", "En attente du Clerc"], ["statut_traitement", "Résolu"],
  ["nature_acte", "Vente immobilière"], ["nature_acte", "Succession"], ["nature_acte", "Donation"],
  ["nature_acte", "Bail commercial"], ["nature_acte", "Vente de terrain urbain"],
  ["progression", "Rédaction"], ["progression", "Formalités"], ["progression", "Signature"],
  ["progression", "État Foncier"], ["progression", "Transmission client"], ["progression", "Terminé"], ["progression", "Annulé"],
  ["statut_paiement", "Réglé"], ["statut_paiement", "Partiel"], ["statut_paiement", "En attente"],
  ["conservation_fonciere", "ABENGOUROU"], ["conservation_fonciere", "ABOBO"], ["conservation_fonciere", "ADZOPE"],
  ["conservation_fonciere", "AGBOVILLE"], ["conservation_fonciere", "BINGERVILLE"], ["conservation_fonciere", "BONDOUKOU"],
  ["conservation_fonciere", "BOUAFLE"], ["conservation_fonciere", "BOUAKE"], ["conservation_fonciere", "COCODY"],
  ["conservation_fonciere", "DABOU"], ["conservation_fonciere", "DALOA"], ["conservation_fonciere", "DIMBOKRO"],
  ["conservation_fonciere", "DIVO"], ["conservation_fonciere", "GAGNOA"], ["conservation_fonciere", "GRAND-BASSAM"],
  ["conservation_fonciere", "GUIGLO"], ["conservation_fonciere", "KORHOGO"], ["conservation_fonciere", "MAN"],
  ["conservation_fonciere", "MARCORY"], ["conservation_fonciere", "ODIENNE"], ["conservation_fonciere", "PLATEAU"],
  ["conservation_fonciere", "RIVIERA"], ["conservation_fonciere", "SAN PEDRO"], ["conservation_fonciere", "SEGUELA"],
  ["conservation_fonciere", "SONGON"], ["conservation_fonciere", "TREICHVILLE"], ["conservation_fonciere", "YAMOUSSOUKRO"],
  ["conservation_fonciere", "YOPOUGON 1"], ["conservation_fonciere", "YOPOUGON 2"],
].map(([type_liste, valeur], i) => ({ type_liste, valeur, ordre: i + 1 }));
